# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 2) do

  create_table "articles", :force => true do |t|
    t.column "title",   :string
    t.column "summary", :text
    t.column "content", :text
  end

  create_table "comments", :force => true do |t|
    t.column "comment",    :text
    t.column "updated_at", :datetime
    t.column "article_id", :integer
  end

end
