#---
# Excerpted from "Ruby on Rails, 2nd Ed."
# We make no guarantees that this code is fit for any purpose. 
# Visit http://www.editions-eyrolles.com/Livre/9782212120790/ for more book information.
#---
# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 4) do

  create_table "line_items", :force => true do |t|
    t.column "product_id", :integer
    t.column "order_id",   :integer
    t.column "quantity",   :integer
    t.column "unit_price", :decimal, :precision => 8, :scale => 2
  end

  create_table "orders", :force => true do |t|
    t.column "name",         :string
    t.column "email",        :string
    t.column "address",      :text
    t.column "pay_type",     :string
    t.column "when_shipped", :datetime
  end

  create_table "products", :force => true do |t|
    t.column "title",          :string
    t.column "description",    :text
    t.column "image_location", :string
    t.column "price",          :decimal,  :precision => 8, :scale => 2
    t.column "date_available", :datetime
  end

end
