#---
# Excerpted from "Ruby on Rails, 2nd Ed."
# We make no guarantees that this code is fit for any purpose. 
# Visit http://www.editions-eyrolles.com/Livre/9782212120790/ for more book information.
#---
# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 4) do

  create_table "details", :force => true do |t|
    t.column "product_id",   :integer
    t.column "sku",          :string
    t.column "manufacturer", :string
  end

  create_table "pictures", :force => true do |t|
    t.column "comment",      :string
    t.column "name",         :string
    t.column "content_type", :string
    t.column "data",         :binary
  end

  create_table "products", :force => true do |t|
    t.column "title",       :string, :limit => 100
    t.column "description", :text
    t.column "image_url",   :text
  end

end
